version: '2'

services:
  php:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile-php5

    volumes:
      - .:/arSql
    links:
      - mysql

  php7:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile-php7

    volumes:
      - .:/arSql
    links:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
