version: '2'

services:
  php:
    build: .
    volumes:
      - .:/arSql
    links:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
